# Yazi base configuration file
[manager]
show_hidden = false
show_symlink = true
scrolloff = 5
mouse_events = [ "click", "scroll" ]
ratio = [ 0, 1, 0 ]

[opener]
edit = [
  { run = 'vide-open "$@"', block = true, desc = "Open in Vide" }
]

[open]
rules = [
  { mime = "*", use = "edit" }
]

